import { createHmac, timingSafeEqual } from 'node:crypto';
import { verifyStripe } from '../../../webhooks/crypto/signature';
import type { ConnectionTestResult, ConnectorConnection, ConnectorDefinition, NormalizedRecord, OAuthAuthorizeUrlResult, OAuthExchangeInput, OAuthExchangeResult, RawWebhookRequest, SourceAdapter, SourcePullResult, SyncCheckpoint } from '../../contracts';
import { StripeApiClient, type StripeCredentials, type StripeFetch } from './stripe.api-client';
import { STRIPE_INCREMENTAL_STREAMS, STRIPE_OAUTH_AUTHORIZE_URL, STRIPE_OAUTH_DEAUTHORIZE_URL, STRIPE_OAUTH_TOKEN_URL, STRIPE_PAGE_SIZE, STRIPE_PROVIDER, STRIPE_WEBHOOK_EVENTS } from './stripe.constants';
import { mapStripeAdjustment, mapStripeCustomer, mapStripeInvoice, mapStripePayment, mapStripeSubscription, mapStripeWebhook } from './stripe.mapper';

const DEFINITION: ConnectorDefinition = { provider: STRIPE_PROVIDER, displayName: 'Stripe', role: 'source', capabilities: ['webhook_ingest', 'initial_backfill', 'incremental_pull'], credentialKind: 'oauth', incrementalStreams: STRIPE_INCREMENTAL_STREAMS };
function credentialsOf(credentials: Record<string, unknown>): StripeCredentials { return { connected_account_id: String(credentials.connected_account_id ?? ''), webhook_secret: String(credentials.webhook_secret ?? ''), livemode: credentials.livemode === true }; }
function stateFor(connection: ConnectorConnection, redirectUri: string): string {
  const secret = process.env.STRIPE_OAUTH_STATE_SECRET ?? ''; if (!secret) throw new Error('STRIPE_OAUTH_STATE_SECRET is required for Stripe OAuth');
  const payload = Buffer.from(JSON.stringify({ workspaceId: connection.workspaceId, connectionId: connection.id, redirectUri, exp: Date.now() + 10 * 60_000 })).toString('base64url');
  const mac = createHmac('sha256', secret).update(payload).digest('base64url'); return `${payload}.${mac}`;
}
function verifyState(connection: ConnectorConnection, redirectUri: string, state: string | undefined): void {
  const secret = process.env.STRIPE_OAUTH_STATE_SECRET ?? ''; if (!state || !secret) throw new Error('invalid Stripe OAuth state'); const [payload, received] = state.split('.'); const expected = createHmac('sha256', secret).update(payload ?? '').digest('base64url'); if (!payload || !received || Buffer.byteLength(received) !== Buffer.byteLength(expected) || !timingSafeEqual(Buffer.from(received), Buffer.from(expected))) throw new Error('invalid Stripe OAuth state'); const decoded = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')) as { workspaceId: string; connectionId: string; redirectUri: string; exp: number }; if (decoded.workspaceId !== connection.workspaceId || decoded.connectionId !== connection.id || decoded.redirectUri !== redirectUri || decoded.exp < Date.now()) throw new Error('expired Stripe OAuth state');
}
function streamPath(stream: string): string { return stream === 'customers' ? '/customers' : stream === 'subscriptions' ? '/subscriptions' : stream === 'invoices' ? '/invoices' : stream === 'payments' ? '/payment_intents' : '/refunds'; }
function mapStream(stream: string, object: Record<string, unknown>): NormalizedRecord { return stream === 'customers' ? mapStripeCustomer(object) : stream === 'subscriptions' ? mapStripeSubscription(object) : stream === 'invoices' ? mapStripeInvoice(object) : stream === 'payments' ? mapStripePayment(object) : mapStripeAdjustment(object); }
async function pull(connection: ConnectorConnection, credentials: Record<string, unknown>, checkpoint: SyncCheckpoint, fetchImpl: StripeFetch, incremental: boolean): Promise<SourcePullResult> {
  const client = new StripeApiClient(credentialsOf(credentials), fetchImpl); const params = new URLSearchParams({ limit: String(STRIPE_PAGE_SIZE) }); if (checkpoint.status === 'running' && checkpoint.cursor) params.set('starting_after', checkpoint.cursor); else if (incremental && checkpoint.cursor) params.set('created[gte]', String(Math.floor(Date.parse(checkpoint.cursor) / 1000)));
  const page = await client.request<{ data: Record<string, unknown>[]; has_more: boolean }>(`${streamPath(checkpoint.streamKey)}?${params.toString()}`); const last = page.data.at(-1) as { id?: string; created?: number } | undefined; const nextCursor = page.has_more ? last?.id ?? null : incremental ? new Date().toISOString() : last?.id ?? checkpoint.cursor;
  return { records: page.data.map((object) => mapStream(checkpoint.streamKey, object)), nextCursor: page.has_more ? nextCursor : new Date().toISOString(), hasMore: page.has_more };
}
export function createStripeAdapter(fetchImpl: StripeFetch = fetch): SourceAdapter {
  return { definition: DEFINITION,
    testConnection: async (_connection, raw): Promise<ConnectionTestResult> => { const credentials = credentialsOf(raw); if (!credentials.connected_account_id || !credentials.webhook_secret) return { ok: false, credentialStatus: 'invalid', checks: { connected_account_id: !!credentials.connected_account_id, webhook_secret: !!credentials.webhook_secret }, message: 'missing connected_account_id or webhook_secret' }; try { await new StripeApiClient(credentials, fetchImpl).request('/account'); return { ok: true, credentialStatus: 'valid', checks: { account_access: true, webhook_secret: true }, message: 'ok' }; } catch (error) { const status = (error as { status?: number }).status; if (status === 401 || status === 403) return { ok: false, credentialStatus: 'invalid', checks: { account_access: false }, message: (error as Error).message, authFailure: true }; throw error; } },
    initialBackfill: (connection, credentials, checkpoint) => pull(connection, credentials, checkpoint, fetchImpl, false), incrementalPull: (connection, credentials, checkpoint) => pull(connection, credentials, checkpoint, fetchImpl, true),
    getOAuthAuthorizeUrl: (connection, redirectUri): OAuthAuthorizeUrlResult => { const clientId = process.env.STRIPE_CONNECT_CLIENT_ID ?? ''; if (!clientId) throw new Error('STRIPE_CONNECT_CLIENT_ID is required for Stripe OAuth'); const query = new URLSearchParams({ response_type: 'code', client_id: clientId, scope: 'read_write', redirect_uri: redirectUri, state: stateFor(connection, redirectUri) }); return { url: `${STRIPE_OAUTH_AUTHORIZE_URL}?${query.toString()}` }; },
    exchangeOAuthCode: async (connection, input: OAuthExchangeInput): Promise<OAuthExchangeResult> => { verifyState(connection, input.redirectUri, input.state); const secret = process.env.STRIPE_SECRET_KEY ?? ''; const clientId = process.env.STRIPE_CONNECT_CLIENT_ID ?? ''; const response = await fetchImpl(STRIPE_OAUTH_TOKEN_URL, { method: 'POST', headers: { Authorization: `Bearer ${secret}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'authorization_code', code: input.code }).toString() }); if (!response.ok) throw Object.assign(new Error(`stripe oauth code exchange failed (${response.status})`), { status: response.status }); const data = await response.json() as { stripe_user_id: string; livemode: boolean; scope: string }; if (!data.stripe_user_id) throw new Error('Stripe OAuth response missing stripe_user_id'); return { credentials: { connected_account_id: data.stripe_user_id, livemode: data.livemode, webhook_secret: '' }, connectionMetadata: { stripe_account_id: data.stripe_user_id, stripe_client_id: clientId, stripe_api_version: '2025-06-30.basil', stripe_account_mode: data.livemode ? 'live' : 'test', stripe_scope: data.scope } }; },
    deauthorize: async (_connection, raw) => { const credentials = credentialsOf(raw); const secret = process.env.STRIPE_SECRET_KEY ?? ''; const clientId = process.env.STRIPE_CONNECT_CLIENT_ID ?? ''; const response = await fetchImpl(STRIPE_OAUTH_DEAUTHORIZE_URL, { method: 'POST', headers: { Authorization: `Bearer ${secret}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: clientId, stripe_user_id: credentials.connected_account_id }).toString() }); if (!response.ok) throw Object.assign(new Error(`stripe deauthorization failed (${response.status})`), { status: response.status }); },
    verifyWebhook: (_connection, raw, request) => { const credentials = credentialsOf(raw); const headers = Object.fromEntries(Object.entries(request.headers).map(([k, v]) => [k, Array.isArray(v) ? v[0] : v])) as Record<string, string | undefined>; const body = request.rawBody ?? Buffer.from(typeof request.body === 'string' ? request.body : JSON.stringify(request.body ?? {})); return verifyStripe({ raw: body, headers, query: {}, secret: credentials.webhook_secret }); },
    normalizeWebhook: (_connection, request) => { const event = request.body as { type?: string; created?: number; data?: { object?: Record<string, unknown> } } | undefined; if (!event?.type || !(STRIPE_WEBHOOK_EVENTS as readonly string[]).includes(event.type) || !event.data?.object) return null; return mapStripeWebhook(event.type, event.data.object, typeof event.created === 'number' ? new Date(event.created * 1000).toISOString() : undefined); },
    isAuthorizationRevokedWebhook: (_connection, request) => (request.body as { type?: string } | undefined)?.type === 'account.application.deauthorized',
  };
}
