import { createHash } from 'node:crypto';
import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { sql } from 'drizzle-orm';
import { DRIZZLE, type Database } from '../auth/database.provider';
import { AuditService } from '../audit/audit.service';
const id=(p:string,...x:string[])=>`${p}_${createHash('sha256').update(x.join('\x1f')).digest('hex').slice(0,26)}`;
@Injectable()
export class DecisionsService {
 constructor(@Inject(DRIZZLE) private readonly db:Database, private readonly audit:AuditService) {}
 async createForOpportunity(workspaceId:string, rows:any[], meta:{radarId:string;connectionId:string;correlationId:string;idempotencyKey:string;policyVersion?:string}) {
  const decisions:any[]=[]; for(const row of rows){ const key=`${meta.idempotencyKey}:${row.customer_id}`; const did=id('dec',workspaceId,key), sid=id('dcs',workspaceId,key); const [existing]=await this.db.execute(sql`select id from decision_records where workspace_id=${workspaceId} and idempotency_key=${key}`) as any[]; if(existing){decisions.push(existing);continue;}
  const [p]=await this.db.execute(sql`select b.definition_version,b.model_version_id,b.score_cutoff,d.outcome_definition_id as target_outcome_definition_id,m.prediction_window_days from opportunity_batches b join radar_model_versions m on m.workspace_id=b.workspace_id and m.id=b.model_version_id join radar_definition_versions d on d.workspace_id=b.workspace_id and d.radar_id=b.radar_id and d.version=b.definition_version where b.workspace_id=${workspaceId} and b.id=${row.batch_id}`) as any[]; if(!p) throw new NotFoundException('decision_prediction_provenance_missing');
   const snapshot={v:1,prediction:{probability:row.probability,band:row.score_band,signals:row.reason_codes,scoreCutoff:p.score_cutoff,modelVersionId:p.model_version_id},commercial:{expectedRevenue:row.expected_revenue,currency:row.currency},destination:{connectionId:meta.connectionId,capability:'outbound_audience'},eligibility:{state:row.eligibility_state}};
   await this.db.transaction(async tx=>{const [score]=await tx.execute(sql`select scoring_cutoff from radar_score_batches where workspace_id=${workspaceId} and radar_id=${meta.radarId} and model_version_id=${p.model_version_id} and scoring_cutoff=${p.score_cutoff}`) as any[];if(!score)throw new NotFoundException('decision_score_batch_missing');await tx.execute(sql`insert into decision_context_snapshots(workspace_id,id,schema_version,snapshot) values(${workspaceId},${sid},1,${JSON.stringify(snapshot)}::jsonb)`);await tx.execute(sql`insert into decision_records(workspace_id,id,customer_id,current_customer_id,radar_id,definition_version,model_version_id,score_batch_id,score_cutoff,opportunity_batch_id,opportunity_row_id,target_outcome_definition_id,policy_version,trigger_source,selected_action_type,context_snapshot_id,decision_batch_id,correlation_id,idempotency_key,reward_window_end) values(${workspaceId},${did},${row.customer_id},${row.customer_id},${meta.radarId},${p.definition_version},${p.model_version_id},${p.score_cutoff},${p.score_cutoff},${row.batch_id},${row.id},${p.target_outcome_definition_id},${meta.policyVersion??'manual-opportunity-action-v1'},'manual_user_action','send_audience',${sid},${id('dcb',workspaceId,meta.idempotencyKey)},${meta.correlationId},${key},now()+(${p.prediction_window_days}||' days')::interval)`);await tx.execute(sql`insert into decision_eligible_actions(workspace_id,decision_id,action_type,action_version,parameters) values(${workspaceId},${did},'do_nothing',1,'{}'),(${workspaceId},${did},'send_audience',1,${JSON.stringify({connectionId:meta.connectionId})}::jsonb)`)});decisions.push({id:did,customerId:row.customer_id}); }
  await this.audit.record({workspaceId,category:'decision',action:'decision.recorded',resourceType:'decision_batch',resourceId:id('dcb',workspaceId,meta.idempotencyKey),metadata:{count:decisions.length,correlationId:meta.correlationId}});return decisions;
 }
 async recordExecution(workspaceId:string,decisionIds:string[], input:{connectionId:string;correlationId:string;idempotencyKey:string;status:string;remoteId?:string;counts:any}){const status=input.status==='success'?'succeeded':input.status==='partial'?'partially_succeeded':input.status;for(const did of decisionIds){const eid=id('aex',workspaceId,input.idempotencyKey,did);await this.db.execute(sql`insert into action_executions(workspace_id,id,decision_id,action_type,action_version,connection_id,correlation_id,idempotency_key,status,remote_id,counts,attempts) values(${workspaceId},${eid},${did},'send_audience',1,${input.connectionId},${input.correlationId},${input.idempotencyKey+':'+did},${status},${input.remoteId??null},${JSON.stringify(input.counts)}::jsonb,1) on conflict(workspace_id,idempotency_key) do update set status=excluded.status,remote_id=excluded.remote_id,counts=excluded.counts,attempts=action_executions.attempts+1,updated_at=now()`)} }
 async reconcileRewards(workspaceId:string){const rows=await this.db.execute(sql`select d.*,coalesce(max(r.version),0)::int rv from decision_records d left join reward_observations r on r.workspace_id=d.workspace_id and r.decision_id=d.id where d.workspace_id=${workspaceId} group by d.workspace_id,d.id`) as any[];for(const d of rows){const [canonical]=await this.db.execute(sql`select coalesce(merged_into_customer_id,id) id from customers where workspace_id=${workspaceId} and id=${d.customer_id}`) as any[];const current=canonical?.id??d.customer_id; if(current!==d.current_customer_id)await this.db.execute(sql`update decision_records set current_customer_id=${current} where workspace_id=${workspaceId} and id=${d.id}`);const o=await this.db.execute(sql`select count(*)::int n,sum(value)::numeric value,count(distinct currency)::int currencies,max(currency) currency,min(observed_at) first,max(observed_at) last from customer_outcomes where workspace_id=${workspaceId} and customer_id in (${d.customer_id},${current}) and outcome_definition_id=${d.target_outcome_definition_id} and deleted_at is null and observed_at>=${d.created_at} and observed_at<=${d.reward_window_end}`) as any[];const x=o[0];const final=new Date(d.reward_window_end)<=new Date();const [last]=await this.db.execute(sql`select * from reward_observations where workspace_id=${workspaceId} and decision_id=${d.id} order by version desc limit 1`) as any[];if(last&&Number(last.outcome_count)===Number(x.n)&&String(last.observed_value??'')===String(x.currencies===1?x.value??'':'')&&Boolean(last.final)===final)continue;await this.db.execute(sql`insert into reward_observations(workspace_id,id,decision_id,version,outcome_count,observed_value,currency,first_outcome_at,last_outcome_at,final,reward_function_version) values(${workspaceId},${id('rwd',workspaceId,d.id,String(d.rv+1))},${d.id},${d.rv+1},${x.n},${x.currencies===1?x.value:null},${x.currencies===1?x.currency:null},${x.first??null},${x.last??null},${final},'target-occurrence-value-v1') on conflict(workspace_id,decision_id,version) do nothing`)} }
 async recordDoNothing(workspaceId:string, decisionId:string, correlationId:string){const [d]=await this.db.execute(sql`select id from decision_records where workspace_id=${workspaceId} and id=${decisionId}`) as any[];if(!d)throw new NotFoundException('decision_not_found');await this.audit.record({workspaceId,category:'decision',action:'decision.do_nothing',resourceType:'decision',resourceId:decisionId,metadata:{correlationId}});return {id:decisionId,status:'not_sent'};}
 async list(workspaceId:string,limit=50){return this.db.execute(sql`select d.*,e.status execution_status,r.outcome_count,r.observed_value,r.currency,r.final from decision_records d left join lateral(select * from action_executions e where e.workspace_id=d.workspace_id and e.decision_id=d.id order by e.updated_at desc limit 1)e on true left join lateral(select * from reward_observations r where r.workspace_id=d.workspace_id and r.decision_id=d.id order by r.version desc limit 1)r on true where d.workspace_id=${workspaceId} order by d.created_at desc,d.id limit ${Math.min(limit,200)}`)}
 async detail(workspaceId:string,id:string){const rows=await this.list(workspaceId,200);const result=(rows as any[]).find((x)=>x.id===id);if(!result)throw new NotFoundException('decision_not_found');return result;}
}
