import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { closeDb, createDb, type Database } from '@truvo/db';
import { sql } from 'drizzle-orm';
import { AuditService } from '../audit/audit.service';
import { DecisionsService } from './decisions.service';
const W='00000000-0000-0000-0000-000000000110', O='00000000-0000-0000-0000-000000000111'; let db:Database, decisions:DecisionsService;
async function seed(){await db.execute(sql`insert into workspaces(id,name,slug) values(${W},'Decision','decision'),(${O},'Other','other-decision')`);await db.execute(sql`insert into outcome_definitions(workspace_id,id,outcome_namespace,outcome_key,name,kind,definition,source_namespace) values(${W},'purchase','canonical','purchase','Purchase','event','{}','test')`);await db.execute(sql`insert into customers(workspace_id,id,status,source_namespace,first_seen_at,last_seen_at) values(${W},'c1','identified','test',now(),now()),(${W},'c2','identified','test',now(),now())`);await db.execute(sql`insert into radars(workspace_id,id,name,status) values(${W},'r1','Radar','active')`);await db.execute(sql`insert into radar_definition_versions(workspace_id,radar_id,version,outcome_definition_id,audience_ast,prediction_window_days,optimization_goal) values(${W},'r1',1,'purchase','{}',30,'{}')`);await db.execute(sql`insert into radar_training_requests(workspace_id,id,radar_id,definition_version,idempotency_key,status,correlation_id) values(${W},'rq','r1',1,'x','succeeded','x')`);await db.execute(sql`insert into radar_model_versions(workspace_id,id,radar_id,definition_version,training_request_id,target_outcome_definition_id,prediction_window_days,status,estimator_type,feature_schema_version,artifact_bucket,artifact_object_key,artifact_reference,artifact_checksum,cutoff_ranges,data_counts,metrics,calibration,selection_reason,verified_at) values(${W},'m1','r1',1,'rq','purchase',30,'active','logistic','v1','b','o','r','0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef','{}','{}','{}','{}','x',now())`);await db.execute(sql`insert into radar_score_batches(workspace_id,radar_id,definition_version,model_version_id,scoring_cutoff,status) values(${W},'r1',1,'m1',now(),'completed')`);await db.execute(sql`insert into opportunity_batches(workspace_id,id,radar_id,definition_version,model_version_id,score_cutoff,policy_version,status,is_current,trigger_reason,row_count,eligible_count,monetary_row_count,materialized_at) select ${W},'b1','r1',1,'m1',scoring_cutoff,'v1','completed',1,'test',2,2,0,now() from radar_score_batches where workspace_id=${W}`);await db.execute(sql`insert into opportunity_rows(workspace_id,id,batch_id,radar_id,customer_id,model_version_id,probability,score_band,scored_at,prediction_window_end,reason_codes,eligibility_state,created_at) values(${W},'o1','b1','r1','c1','m1',.8,'high',now(),now()+interval '30 days','[]','eligible',now()),(${W},'o2','b1','r1','c2','m1',.7,'high',now(),now()+interval '30 days','[]','eligible',now())`)}
before(async()=>{if(!process.env.DATABASE_URL)throw Error('DATABASE_URL required');db=createDb();decisions=new DecisionsService(db,new AuditService(db));await seed()});after(async()=>{await closeDb(db)});
test('Decision immutable provenance, idempotency, do-nothing, rewards, identity and tenant isolation',async()=>{const rows=await db.execute(sql`select * from opportunity_rows where workspace_id=${W}`) as any[];const first=await decisions.createForOpportunity(W,rows,{radarId:'r1',connectionId:'dest',correlationId:'corr',idempotencyKey:'activation'});const replay=await decisions.createForOpportunity(W,rows,{radarId:'r1',connectionId:'dest',correlationId:'corr',idempotencyKey:'activation'});assert.equal(first.length,2);assert.equal(replay.length,2);const [count]=await db.execute(sql`select count(*)::int n from decision_records where workspace_id=${W}`) as any[];assert.equal(count.n,2);await decisions.recordExecution(W,[first[0].id],{connectionId:'dest',correlationId:'corr',idempotencyKey:'send',status:'succeeded',remoteId:'a555',counts:{requested:1,succeeded:1}});await decisions.recordDoNothing(W,first[1].id,'none');await db.execute(sql`insert into customer_outcomes(workspace_id,id,customer_id,outcome_definition_id,outcome_namespace,outcome_key,dedupe_key,event_id,value,currency,source_namespace,observed_at) values(${W},'p77','c1','purchase','canonical','purchase','d77','e77',149.90,'BRL','test',now())`);await decisions.reconcileRewards(W);const [reward]=await db.execute(sql`select * from reward_observations where workspace_id=${W} and decision_id=${first[0].id}`) as any[];assert.equal(reward.outcome_count,1);assert.equal(reward.currency,'BRL');await db.execute(sql`update customers set status='merged',merged_into_customer_id='c1' where workspace_id=${W} and id='c2'`);await decisions.reconcileRewards(W);const list=await decisions.list(W);assert.equal(list.length,2);assert.equal((await decisions.list(O)).length,0);const pii=await db.execute(sql`select count(*)::int n from information_schema.columns where table_name='decision_context_snapshots' and column_name in ('email','phone','token')`) as any[];assert.equal(pii[0].n,0)});
