import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { expect, test } from '@playwright/test';

const workspace = 'workspace-onboarding-e2e'; let server: ReturnType<typeof createServer>; let step = 'workspace_basics'; let radarCreates = 0;
const progress = () => ({ progress: { current_step: step, status: step === 'completed' ? 'completed' : 'in_progress', selected_path: step === 'workspace_basics' || step === 'choose_path' ? null : 'custom' }, source: { state: 'custom', healthy: true, provider: 'truvo_events' }, ttfvMs: step === 'completed' ? 1200 : null, recommendations: { ecommerce: ['shopify'], saas: ['stripe'], custom: ['truvo_events'] } });
async function body(req: IncomingMessage) { const chunks: Buffer[]=[]; for await (const c of req) chunks.push(Buffer.from(c)); return chunks.length ? JSON.parse(Buffer.concat(chunks).toString()) : {}; }
function json(res: ServerResponse, value: unknown, status=200) { res.writeHead(status, {'content-type':'application/json','access-control-allow-origin':'http://127.0.0.1:3100','access-control-allow-headers':'content-type,authorization,x-workspace-id'}); res.end(JSON.stringify(value)); }
test.beforeAll(async () => { server=createServer(async(req,res)=>{ if(req.method==='OPTIONS') return json(res,{}); const path=new URL(req.url!,'http://localhost').pathname; if(path==='/v1/users/me') return json(res,{id:'user',email:'onboarding@truvo.test',workspaces:[{id:workspace,name:'Fresh workspace'}]}); if(req.headers['x-workspace-id']!==workspace) return json(res,{message:'denied'},403); if(path.includes('/connectors/connections')) return json(res,[]); if(path==='/v1/radars/metadata/outcomes') return json(res,[{id:'purchase',name:'Compra real'}]); if(path==='/v1/onboarding'&&req.method==='GET') return json(res,progress()); if(path==='/v1/onboarding/start'){step='choose_path';return json(res,progress());} if(path==='/v1/onboarding/path'){await body(req);step='connect_context';return json(res,progress());} if(path==='/v1/onboarding/verify'){step='readiness';return json(res,{...progress(),detected:true,counts:{customers:1}});} if(path==='/v1/onboarding/readiness'){step='create_radar';return json(res,{...progress(),readiness:{radarReadiness:{status:'not_ready',reasonCodes:['insufficient_history']}}});} if(path==='/v1/onboarding/radar'){radarCreates++;step='completed';return json(res,{...progress(),radar:{radar:{id:'rad_first'}},replay:radarCreates>1});} return json(res,{message:'not found'},404);}); await new Promise<void>(r=>server.listen(3101,'127.0.0.1',r)); });
test.afterAll(async()=>{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));});
test.beforeEach(async({page})=>{step='workspace_basics';radarCreates=0;await page.addInitScript(({workspace})=>{localStorage.setItem('truvo_mode','live');localStorage.setItem('truvo_token','production-shaped-jwt');localStorage.setItem('truvo_workspace',workspace);}, {workspace});await page.goto('/');await page.getByRole('button',{name:'Launch Setup Wizard'}).click();});

test('guided custom path resumes, reports insufficient history and reaches the real Radar destination',async({page})=>{
  await page.getByLabel('Nome do workspace').fill('Acme Revenue'); await page.getByRole('button',{name:/Continuar/}).click();
  await page.getByRole('button',{name:/Eventos personalizados/}).click(); await expect(page.getByText('Envie um evento real')).toBeVisible();
  await page.reload(); await page.getByRole('button',{name:'Launch Setup Wizard'}).click(); await expect(page.getByText('Envie um evento real')).toBeVisible();
  await page.getByRole('button',{name:'Verificar dados recebidos'}).click(); await page.getByRole('button',{name:'Ver prontidão'}).click();
  await expect(page.getByText(/ainda não há histórico suficiente/)).toBeVisible(); await page.getByRole('button',{name:'Criar Radar real'}).click();
  await expect(page.getByText('Seu primeiro Radar foi criado')).toBeVisible(); await page.getByRole('button',{name:'Ver Radars'}).click(); await expect(page.getByRole('heading',{name:'Quem vai comprar a seguir?'})).toBeVisible(); expect(radarCreates).toBe(1);
});
