import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { expect, test } from '@playwright/test';

const workspace = 'workspace-onboarding-e2e'; const workspaceB = 'workspace-onboarding-b'; let server: ReturnType<typeof createServer>; let step = 'workspace_basics'; let radarCreates = 0; let onboardingCalls = 0; let delayA = false; let failB = false; let releaseA: (() => void) | null = null; let callsA = 0; let callsB = 0;
const progress = () => ({ progress: { current_step: step, status: step === 'completed' ? 'completed' : 'in_progress', selected_path: step === 'workspace_basics' || step === 'choose_path' ? null : 'custom' }, source: { state: 'custom', healthy: true, provider: 'truvo_events' }, ttfvMs: step === 'completed' ? 1200 : null, recommendations: { ecommerce: ['shopify'], saas: ['stripe'], custom: ['truvo_events'] } });
async function body(req: IncomingMessage) { const chunks: Buffer[]=[]; for await (const c of req) chunks.push(Buffer.from(c)); return chunks.length ? JSON.parse(Buffer.concat(chunks).toString()) : {}; }
function json(res: ServerResponse, value: unknown, status=200) { res.writeHead(status, {'content-type':'application/json','access-control-allow-origin':'http://127.0.0.1:3100','access-control-allow-headers':'content-type,authorization,x-workspace-id'}); res.end(JSON.stringify(value)); }
test.beforeAll(async () => { server=createServer(async(req,res)=>{ if(req.method==='OPTIONS') return json(res,{}); const path=new URL(req.url!,'http://localhost').pathname; if(path==='/v1/users/me') return json(res,{id:'user',email:'onboarding@truvo.test',workspaces:[{id:workspace,name:'Workspace A'},{id:workspaceB,name:'Workspace B'}]}); const ws=String(req.headers['x-workspace-id'] ?? ''); if(![workspace,workspaceB].includes(ws)) return json(res,{message:'denied'},403); if(path.includes('/connectors/connections')) return json(res,ws===workspaceB?[{id:'conn-b',provider:'stripe',displayName:'Only B',lifecycleState:'syncing',credentialStatus:'valid'}]:[]); if(path==='/v1/radars/metadata/outcomes') return json(res,ws===workspaceB?[{id:'renewal-b',name:'Renewal B'}]:[{id:'purchase',name:'Compra real'}]); if(path==='/v1/onboarding'&&req.method==='GET'){onboardingCalls++; if(delayA&&ws===workspace){callsA++;await new Promise<void>(r=>{releaseA=r;});return json(res,{...progress(),progress:{...progress().progress,current_step:'connect_context',selected_path:'custom'}});} if(ws===workspaceB){callsB++;if(failB)return json(res,{message:'B unavailable'},503);return json(res,{...progress(),progress:{...progress().progress,current_step:'verify_data',status:'syncing',selected_path:'saas'},source:{state:'syncing',healthy:false,provider:'stripe'}});} return json(res,progress());} if(path==='/v1/onboarding/start'){step='choose_path';return json(res,progress());} if(path==='/v1/onboarding/path'){await body(req);step='connect_context';return json(res,progress());} if(path==='/v1/onboarding/verify'){step='readiness';return json(res,{...progress(),detected:true,counts:{customers:1}});} if(path==='/v1/onboarding/readiness'){step='create_radar';return json(res,{...progress(),readiness:{radarReadiness:{status:'not_ready',reasonCodes:['insufficient_history']}}});} if(path==='/v1/onboarding/radar'){radarCreates++;step='completed';return json(res,{...progress(),radar:{radar:{id:'rad_first'}},replay:radarCreates>1});} return json(res,{message:'not found'},404);}); await new Promise<void>(r=>server.listen(3101,'127.0.0.1',r)); });
test.afterAll(async()=>{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));});
test.beforeEach(async({page},testInfo)=>{step='workspace_basics';radarCreates=0;onboardingCalls=0;delayA=false;failB=false;releaseA=null;callsA=0;callsB=0;if(!testInfo.title.includes('demo'))await page.addInitScript(({workspace})=>{localStorage.setItem('truvo_mode','live');localStorage.setItem('truvo_token','production-shaped-jwt');localStorage.setItem('truvo_workspace',workspace);}, {workspace});await page.goto('/');if(!testInfo.title.includes('demo'))await page.getByRole('button',{name:'Launch Setup Wizard'}).click();});

test('guided custom path resumes, reports insufficient history and reaches the real Radar destination',async({page})=>{
  await page.getByLabel('Nome do workspace').fill('Acme Revenue'); await page.getByRole('button',{name:/Continuar/}).click();
  await page.getByRole('button',{name:/Eventos personalizados/}).click(); await expect(page.getByText('Envie um evento real')).toBeVisible();
  await page.reload(); await page.getByRole('button',{name:'Launch Setup Wizard'}).click(); await expect(page.getByText('Envie um evento real')).toBeVisible();
  await page.getByRole('button',{name:'Verificar dados recebidos'}).click(); await page.getByRole('button',{name:'Ver prontidão'}).click();
  await expect(page.getByText(/ainda não há histórico suficiente/)).toBeVisible(); await page.getByRole('button',{name:'Criar Radar real'}).click();
  await expect(page.getByText('Seu primeiro Radar foi criado')).toBeVisible(); await page.getByRole('button',{name:'Ver Radars'}).click(); await expect(page.getByRole('heading',{name:'Quem vai comprar a seguir?'})).toBeVisible(); expect(radarCreates).toBe(1);
});

test('explicit demo renders synthetic mode without any live onboarding request',async({page})=>{
  await page.getByRole('button',{name:'Entrar na demonstração'}).click(); await expect(page.getByText('Modo demonstração — dados sintéticos')).toBeVisible();
  await expect(page.getByText('Multi-Channel Attribution Feed')).toBeVisible(); expect(onboardingCalls).toBe(0);
  await page.getByRole('button',{name:'Launch Setup Wizard'}).click(); expect(onboardingCalls).toBe(0); await expect(page.getByText('Modo demonstração — dados sintéticos')).toBeVisible();
});

test('workspace B rejects delayed A state, data and polling after switch',async({page})=>{
  await page.getByTestId('onboarding-flow').getByRole('button',{name:'Sair',exact:true}).click(); delayA=true; await page.getByRole('button',{name:'Launch Setup Wizard'}).click();
  await expect.poll(()=>callsA).toBeGreaterThanOrEqual(1); await page.locator('#workspace-switcher-btn').click(); await page.getByRole('button',{name:'Workspace B'}).click();
  await expect(page.getByText('Estamos verificando seu Contexto')).toBeVisible(); await expect(page.getByText('Fonte: syncing.')).toBeVisible(); releaseA?.();
  await expect(page.getByText('Estamos verificando seu Contexto')).toBeVisible(); await expect(page.getByText('Envie um evento real')).toHaveCount(0); await expect(page.getByText('Only B')).toHaveCount(0);
  const callsAAfterSwitch = callsA; await page.waitForTimeout(5200); expect(callsA).toBe(callsAAfterSwitch); expect(callsB).toBeGreaterThanOrEqual(2);
  delayA=false; await page.locator('#workspace-switcher-btn').click(); await page.getByRole('button',{name:'Workspace A'}).click(); await expect(page.getByLabel('Nome do workspace')).toBeVisible();
  failB=true; await page.locator('#workspace-switcher-btn').click(); await page.getByRole('button',{name:'Workspace B'}).click(); await expect(page.getByText('B unavailable',{exact:true})).toBeVisible(); await expect(page.getByLabel('Nome do workspace')).toHaveCount(0);
});
