import test from 'node:test';
import assert from 'node:assert/strict';
import { closeDb, createDb } from '@truvo/db';
import { sql } from 'drizzle-orm';
import { EventContextQualityService, validateEventQuality } from './event-context-quality.service';

const url = process.env.DATABASE_URL;
test('ORDER_070 populated Postgres runtime matrix', async () => {
  if (!url) throw new Error('DATABASE_URL is required; run against disposable Postgres 16');
  const db = createDb();
  const a = `070-a-${Date.now()}`; const b = `070-b-${Date.now()}`; const now = new Date(); const old = new Date(now.getTime() - 72 * 60 * 60_000);
  await db.execute(sql`insert into customers (workspace_id,id,status,source_namespace,first_seen_at,last_seen_at) values (${a},'c1','identified','fixture',now(),now()),(${a},'c2','anonymous','fixture',now(),now()),(${b},'c1','identified','fixture',now(),now())`);
  await db.execute(sql`insert into customer_identifiers (workspace_id,id,customer_id,identifier_type,provider_namespace,identifier_value,source_namespace,first_seen_at,last_seen_at) values (${a},'i1','c1','email_hash','fixture','hash-c1','fixture',now(),now()),(${b},'i1','c1','email_hash','fixture','hash-c1','fixture',now(),now())`);
  await db.execute(sql`insert into connector_connections (workspace_id,id,provider,role,display_name,lifecycle_state,credential_status,last_sync_at) values (${a},'stale','fixture','source','Stale','healthy','valid',${old.toISOString()}),(${a},'limited','fixture','source','Limited','healthy','valid',${old.toISOString()}),(${a},'off','fixture','source','Revoked','disconnected','expired',now()),(${b},'stale','fixture','source','Stale','healthy','valid',now())`);
  await db.execute(sql`insert into connector_sync_checkpoints (workspace_id,connection_id,stream_key,cursor,status,updated_at) values (${a},'stale','events','10','completed',${old.toISOString()}),(${a},'limited','events','11','completed',${old.toISOString()})`);
  await db.execute(sql`insert into connector_sync_runs (workspace_id,id,connection_id,kind,idempotency_key,status,attempt,created_at) values (${a},'r1','limited','webhook_ingest','delivery-1','rate_limited',2,now())`);
  await db.execute(sql`insert into engagement_events (workspace_id,id,connection_id,customer_id,provider_namespace,provider_event_id,metric_name,engagement_kind,occurred_at) values (${a},'e1','stale','c1','fixture','provider-e1','open','opened',now())`);
  const service = new EventContextQualityService(db);
  const first = await service.evaluate(a, { requiredDimensions: ['identity'], outcomeKey: 'purchase', historicalWindowDays: 7 });
  assert.equal(first.contextCoverage.dimensions.identity.eligible, 2);
  assert.equal(first.contextCoverage.dimensions.identity.observed, 1);
  assert.equal(first.contextCoverage.dimensions.identity.coverage, 0.5);
  assert.equal(first.issues.some((i) => i.stableKey === `source:stale:stale`), true);
  assert.equal(first.issues.some((i) => i.stableKey === `source:disconnected:off` && i.actionCode === 'reconnect_source'), true);
  assert.equal(first.sourceFreshness.some((s) => (s as { state?: string }).state === 'rate_limited_backoff'), true);
  assert.equal(first.radarReadiness.status, 'not_ready');
  assert.equal(first.radarReadiness.reasonCodes.includes('insufficient_outcome_history'), true);
  assert.equal(first.dataHealth.score, 30);
  assert.equal(first.dataHealth.status, 'blocker');
  assert.equal(first.contextCoverage.score, 21);
  const persisted = await service.getSummary(a) as { data_health_score: number; context_coverage_score: number };
  assert.equal(persisted.data_health_score, 30);
  assert.equal(persisted.context_coverage_score, 21);
  assert.equal(first.duplicateSummary.deliveryReplayAttempts, 1);
  assert.equal(first.duplicateSummary.canonicalNaturalKeyDefects, 0);
  assert.equal(validateEventQuality({ eventName: 'unknown', identifiers: {}, properties: {} }, { knownEventNames: ['signup'], requiredProperties: { amount: 'number' } }).length >= 3, true);
  const second = await service.evaluate(a, { requiredDimensions: ['identity'], outcomeKey: 'purchase' });
  assert.equal(second.issues.length, first.issues.length);
  const issueRows = await service.listIssues(a, 'active');
  assert.equal(issueRows.length, first.issues.length);
  const tenantRows = await service.listIssues(b, 'active');
  assert.equal(tenantRows.length, 0);
  await db.execute(sql`update connector_connections set lifecycle_state='healthy', credential_status='valid', last_sync_at=now() where workspace_id=${a} and id='off'`);
  await db.execute(sql`update connector_sync_checkpoints set updated_at=now() where workspace_id=${a} and connection_id='stale'`);
  const resolved = await service.evaluate(a);
  assert.equal(resolved.issues.some((i) => i.stableKey === 'source:disconnected:off'), false);
  const resolvedRow = await db.execute(sql`select status from quality_issues where workspace_id=${a} and stable_key='source:disconnected:off'`);
  assert.equal((resolvedRow[0] as { status: string }).status, 'resolved');
  assert.equal(resolved.dataHealth.score, 100);
  assert.equal(resolved.contextCoverage.score, 21);
  assert.equal(resolved.radarReadiness.status, 'ready');
  const stableReadback = await service.getSummary(a) as { data_health_score: number; context_coverage_score: number };
  assert.equal(stableReadback.data_health_score, 100);
  assert.equal(stableReadback.context_coverage_score, 21);
  const canonical = await db.execute(sql`select count(*)::int as count from customers where workspace_id=${a}`);
  assert.equal(Number((canonical[0] as { count: number }).count), 2);
  await db.execute(sql`delete from quality_evaluations where workspace_id in (${a},${b})`);
  await db.execute(sql`delete from quality_issues where workspace_id in (${a},${b})`);
  await db.execute(sql`delete from engagement_events where workspace_id in (${a},${b})`);
  await db.execute(sql`delete from connector_sync_runs where workspace_id in (${a},${b})`);
  await db.execute(sql`delete from connector_sync_checkpoints where workspace_id in (${a},${b})`);
  await db.execute(sql`delete from connector_connections where workspace_id in (${a},${b})`);
  await db.execute(sql`delete from customer_identifiers where workspace_id in (${a},${b})`);
  await db.execute(sql`delete from customers where workspace_id in (${a},${b})`);
  await closeDb(db);
});
