import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { sql } from 'drizzle-orm';
import { DRIZZLE, type Database } from '../auth/database.provider';
import { EventContextQualityService } from '../data-quality/event-context-quality.service';

export const RADAR_WINDOWS = [7, 14, 30, 60] as const;
export const DEFAULT_AUDIENCE = { version: 1, op: 'identified' } as const;
export const RADAR_MINIMUM_DATA_POLICY = { minLabeledExamples: Number(process.env.RADAR_MIN_LABELED_EXAMPLES ?? 1000), minPositives: Number(process.env.RADAR_MIN_POSITIVES ?? 100), minNegatives: Number(process.env.RADAR_MIN_NEGATIVES ?? 100) };
const transitions: Record<string, string[]> = { draft: ['validating_data', 'archived'], validating_data: ['ready_to_train', 'insufficient_data', 'failed'], insufficient_data: ['validating_data', 'archived'], ready_to_train: ['training', 'paused', 'archived', 'validating_data'], training: ['active', 'failed'], active: ['paused', 'archived', 'validating_data'], paused: ['ready_to_train', 'archived', 'validating_data'], failed: ['validating_data', 'archived'], archived: [] };
export type AudienceAst = { version: 1; op: 'identified' } | { version: 1; op: 'trait'; key: string; operator: 'eq' | 'exists'; value?: string | number | boolean } | { version: 1; op: 'outcome_occurred'; outcomeDefinitionId: string } | { version: 1; op: 'and' | 'or'; children: AudienceAst[] };
export type ActivationDestination = { connectionId: string; capability: 'activation' };
export function validateAudienceAst(ast: unknown): AudienceAst {
  if (typeof ast === 'string') { try { ast = JSON.parse(ast); } catch { throw new BadRequestException('Invalid audience AST JSON'); } }
  if (!ast || typeof ast !== 'object' || (ast as { version?: unknown }).version !== 1) throw new BadRequestException('Invalid audience AST version'); const node = ast as Record<string, unknown>;
  if (node.op === 'identified') return node as AudienceAst;
  if (node.op === 'trait' && typeof node.key === 'string' && /^[a-z][a-z0-9_]{0,63}$/.test(node.key) && (node.operator === 'exists' || (node.operator === 'eq' && ['string','number','boolean'].includes(typeof node.value)))) return node as AudienceAst;
  if (node.op === 'outcome_occurred' && typeof node.outcomeDefinitionId === 'string' && node.outcomeDefinitionId.length > 0) return node as AudienceAst;
  if ((node.op === 'and' || node.op === 'or') && Array.isArray(node.children) && node.children.length >= 2 && node.children.length <= 8) return { version: 1, op: node.op, children: node.children.map(validateAudienceAst) } as AudienceAst;
  throw new BadRequestException('Invalid canonical audience predicate');
}
@Injectable()
export class RadarService {
  constructor(@Inject(DRIZZLE) private readonly db: Database, private readonly quality: EventContextQualityService) {}
  private async radar(workspaceId: string, id: string) { const [r] = await this.db.execute(sql`select * from radars where workspace_id=${workspaceId} and id=${id}`); if (!r) throw new NotFoundException('Radar not found'); return r as { id: string; status: string; current_definition_version: number }; }
  async create(workspaceId: string, input: { name: string; outcomeDefinitionId: string; audienceAst?: unknown; predictionWindowDays: number; optimizationGoal?: Record<string, unknown>; activationDestination?: ActivationDestination }) {
    if (!RADAR_WINDOWS.includes(input.predictionWindowDays as 7)) throw new BadRequestException('Prediction window must be 7, 14, 30, or 60 days'); const audience = validateAudienceAst(input.audienceAst ?? DEFAULT_AUDIENCE);
    const [outcome] = await this.db.execute(sql`select id from outcome_definitions where workspace_id=${workspaceId} and id=${input.outcomeDefinitionId} and is_active=true and deleted_at is null`); if (!outcome) throw new BadRequestException('Target outcome is not an active canonical outcome definition');
    const destination = await this.validateDestination(workspaceId, input.activationDestination); const id = `rad_${randomUUID()}`; await this.db.execute(sql`insert into radars (workspace_id,id,name,status,current_definition_version) values (${workspaceId},${id},${input.name},'draft',1)`);
    await this.db.execute(sql`insert into radar_definition_versions (workspace_id,radar_id,version,outcome_definition_id,audience_ast,prediction_window_days,optimization_goal,activation_destination) values (${workspaceId},${id},1,${input.outcomeDefinitionId},${JSON.stringify(audience)}::jsonb,${input.predictionWindowDays},${JSON.stringify(input.optimizationGoal ?? {})}::jsonb,${JSON.stringify(destination)}::jsonb)`); return this.get(workspaceId, id);
  }
  async get(workspaceId: string, id: string) { const radar = await this.radar(workspaceId, id); const [definition] = await this.db.execute(sql`select * from radar_definition_versions where workspace_id=${workspaceId} and radar_id=${id} and version=${radar.current_definition_version}`); return { radar, definition }; }
  async list(workspaceId: string) { return this.db.execute(sql`select r.*, d.outcome_definition_id, d.prediction_window_days from radars r join radar_definition_versions d on d.workspace_id=r.workspace_id and d.radar_id=r.id and d.version=r.current_definition_version where r.workspace_id=${workspaceId} order by r.updated_at desc`); }
  async availableOutcomes(workspaceId: string) { return this.db.execute(sql`select id,name,outcome_namespace,outcome_key,kind from outcome_definitions where workspace_id=${workspaceId} and is_active=true and deleted_at is null order by name`); }
  audienceMetadata() { return { version: 1, fields: [{ kind: 'identified', operators: ['exists'] }, { kind: 'trait', operators: ['eq', 'exists'], keyPattern: '^[a-z][a-z0-9_]{0,63}$' }, { kind: 'outcome_occurred', operators: ['exists'] }], logical: ['and', 'or'] }; }
  async activationDestinations(workspaceId: string) { return this.db.execute(sql`select id,provider,display_name,lifecycle_state,capabilities from connector_connections where workspace_id=${workspaceId} and role in ('destination','bidirectional') and 'activation' = any(select jsonb_array_elements_text(capabilities)) order by display_name`); }
  async audienceCount(workspaceId: string, ast: unknown): Promise<number> { const ids = await this.audienceIds(workspaceId, validateAudienceAst(ast)); return ids.size; }
  private async audienceIds(workspaceId: string, ast: AudienceAst): Promise<Set<string>> { if (ast.op === 'identified') { const rows = await this.db.execute(sql`select id from customers where workspace_id=${workspaceId} and status='identified' and deleted_at is null`); return new Set((rows as unknown as { id:string }[]).map(r=>r.id)); }
    if (ast.op === 'trait') { const rows = ast.operator === 'exists' ? await this.db.execute(sql`select customer_id from customer_traits where workspace_id=${workspaceId} and trait_key=${ast.key} and deleted_at is null`) : await this.db.execute(sql`select customer_id from customer_traits where workspace_id=${workspaceId} and trait_key=${ast.key} and value::text=${JSON.stringify(ast.value)} and deleted_at is null`); return new Set((rows as unknown as { customer_id:string }[]).map(r=>r.customer_id)); }
    if (ast.op === 'outcome_occurred') { const rows = await this.db.execute(sql`select distinct customer_id from customer_outcomes where workspace_id=${workspaceId} and outcome_definition_id=${ast.outcomeDefinitionId} and deleted_at is null`); return new Set((rows as unknown as { customer_id:string }[]).map(r=>r.customer_id)); }
    const groups = await Promise.all(ast.children.map((child)=>this.audienceIds(workspaceId,child))); if (ast.op === 'or') return new Set(groups.flatMap((s)=>[...s])); return new Set([...groups[0]].filter((id)=>groups.every((s)=>s.has(id)))); }
  async validate(workspaceId: string, id: string) { const { radar, definition } = await this.get(workspaceId, id) as unknown as { radar: { status: string; current_definition_version: number }; definition: { outcome_definition_id: string; prediction_window_days: number } }; this.transition(radar.status, 'validating_data'); await this.setStatus(workspaceId, id, 'validating_data');
    const [counts] = await this.db.execute(sql`select count(distinct c.id)::int as eligible, count(distinct o.customer_id)::int as positives, count(distinct c.id)::int - count(distinct o.customer_id)::int as negatives from customers c left join customer_outcomes o on o.workspace_id=c.workspace_id and o.customer_id=c.id and o.outcome_definition_id=${definition.outcome_definition_id} and o.deleted_at is null where c.workspace_id=${workspaceId} and c.status='identified' and c.deleted_at is null`);
    const q = await this.quality.evaluate(workspaceId, { requiredDimensions: ['identity'], outcomeKey: 'radar' }); const c = counts as { eligible: number; positives: number; negatives: number }; const reasons: string[] = []; if (c.eligible < RADAR_MINIMUM_DATA_POLICY.minLabeledExamples) reasons.push('insufficient_labeled_examples'); if (c.positives < RADAR_MINIMUM_DATA_POLICY.minPositives) reasons.push('insufficient_positive_outcomes'); if (c.negatives < RADAR_MINIMUM_DATA_POLICY.minNegatives) reasons.push('insufficient_negative_examples'); if (q.criticalCount) reasons.push('quality_blockers'); const status = reasons.length ? 'insufficient_data' : 'ready_to_train'; await this.setStatus(workspaceId, id, status); const readiness = { status, eligibleCustomerCount: Number(c.eligible), positiveOutcomeCount: Number(c.positives), negativeCount: Number(c.negatives), policy: RADAR_MINIMUM_DATA_POLICY, quality: q, reasonCodes: reasons }; await this.db.execute(sql`update radar_definition_versions set readiness=${JSON.stringify(readiness)}::jsonb where workspace_id=${workspaceId} and radar_id=${id} and version=${radar.current_definition_version}`); return readiness;
  }
  async train(workspaceId: string, id: string, key: string) { const r = await this.radar(workspaceId, id); const existing = await this.db.execute(sql`select * from radar_training_requests where workspace_id=${workspaceId} and radar_id=${id} and definition_version=${r.current_definition_version}`); if (existing[0]) return existing[0]; if (r.status !== 'ready_to_train') throw new BadRequestException('Radar is not ready to train'); const reqId = `rtr_${randomUUID()}`; const correlation = randomUUID(); const rows = await this.db.execute(sql`insert into radar_training_requests (workspace_id,id,radar_id,definition_version,idempotency_key,status,correlation_id) values (${workspaceId},${reqId},${id},${r.current_definition_version},${key},'accepted',${correlation}) on conflict (workspace_id,radar_id,definition_version) do update set updated_at=now() returning *`); await this.setStatus(workspaceId, id, 'training'); return rows[0]; }
  async reportTrainingResult(workspaceId: string, id: string, version: number, requestId: string, result: { status: 'succeeded' | 'failed'; modelReference?: string; failureReason?: string }) { const r = await this.radar(workspaceId, id); const [request] = await this.db.execute(sql`select * from radar_training_requests where workspace_id=${workspaceId} and id=${requestId} and radar_id=${id} and definition_version=${version}`); if (!request) throw new BadRequestException('Training request does not match Radar definition'); if (r.current_definition_version !== version || r.status !== 'training') throw new BadRequestException('Stale training result cannot change current Radar'); if (result.status === 'succeeded') { if (!result.modelReference?.trim()) throw new BadRequestException('Successful training result requires model reference'); await this.db.execute(sql`update radar_training_requests set status='succeeded',model_reference=${result.modelReference},updated_at=now() where workspace_id=${workspaceId} and id=${requestId}`); await this.db.execute(sql`update radars set status='active',current_model_reference=${result.modelReference},updated_at=now() where workspace_id=${workspaceId} and id=${id}`); } else { await this.db.execute(sql`update radar_training_requests set status='failed',failure_reason=${result.failureReason?.slice(0, 500) ?? 'training_failed'},updated_at=now() where workspace_id=${workspaceId} and id=${requestId}`); await this.setStatus(workspaceId,id,'failed'); } }
  async patch(workspaceId: string, id: string, input: { name?: string; outcomeDefinitionId?: string; audienceAst?: unknown; predictionWindowDays?: number; activationDestination?: ActivationDestination }) { const r = await this.radar(workspaceId, id); if (input.name && !input.outcomeDefinitionId && !input.audienceAst && !input.predictionWindowDays && !input.activationDestination) { await this.db.execute(sql`update radars set name=${input.name},updated_at=now() where workspace_id=${workspaceId} and id=${id}`); return this.get(workspaceId, id); } const current = await this.get(workspaceId, id) as unknown as { definition: { outcome_definition_id: string; audience_ast: unknown; prediction_window_days: number } }; const next = r.current_definition_version + 1; const window = input.predictionWindowDays ?? current.definition.prediction_window_days; if (!RADAR_WINDOWS.includes(window as 7)) throw new BadRequestException('Invalid prediction window'); const audience = validateAudienceAst(input.audienceAst ?? current.definition.audience_ast); const outcome = input.outcomeDefinitionId ?? current.definition.outcome_definition_id; const destination = await this.validateDestination(workspaceId,input.activationDestination); await this.db.execute(sql`insert into radar_definition_versions (workspace_id,radar_id,version,outcome_definition_id,audience_ast,prediction_window_days,optimization_goal,activation_destination) values (${workspaceId},${id},${next},${outcome},${JSON.stringify(audience)}::jsonb,${window},'{}'::jsonb,${JSON.stringify(destination)}::jsonb)`); await this.db.execute(sql`update radars set current_definition_version=${next},current_model_reference=null,status='draft',updated_at=now() where workspace_id=${workspaceId} and id=${id}`); return this.get(workspaceId, id); }
  async action(workspaceId: string, id: string, target: 'paused' | 'archived') { const r = await this.radar(workspaceId, id); this.transition(r.status, target); await this.setStatus(workspaceId, id, target); }
  private transition(from: string, to: string) { if (!transitions[from]?.includes(to)) throw new BadRequestException(`Illegal Radar transition: ${from} -> ${to}`); }
  private async validateDestination(workspaceId:string, destination?:ActivationDestination) { if (!destination) return null; if (destination.capability !== 'activation') throw new BadRequestException('Unsupported activation capability'); const [connection] = await this.db.execute(sql`select id,lifecycle_state,capabilities from connector_connections where workspace_id=${workspaceId} and id=${destination.connectionId} and role in ('destination','bidirectional')`); if (!connection || !Array.isArray((connection as {capabilities?:unknown}).capabilities) || !(connection as {capabilities:string[]}).capabilities.includes('activation')) throw new BadRequestException('Activation destination is not a compatible workspace connection'); return { connectionId: destination.connectionId, capability: 'activation', activationReady: (connection as {lifecycle_state:string}).lifecycle_state !== 'disconnected' }; }
  private async setStatus(workspaceId: string, id: string, status: string) { await this.db.execute(sql`update radars set status=${status},paused_at=${status === 'paused' ? sql`now()` : null},archived_at=${status === 'archived' ? sql`now()` : null},updated_at=now() where workspace_id=${workspaceId} and id=${id}`); }
}
