import test from 'node:test'; import assert from 'node:assert/strict'; import { closeDb, createDb } from '@truvo/db'; import { sql } from 'drizzle-orm'; import { RadarService } from './radar.service';
test('Radar runtime: canonical audiences, destination isolation and training version safety', async () => {
  if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL required for Radar runtime test'); const db=createDb(); const a='00000000-0000-0000-0000-000000000801'; const b='00000000-0000-0000-0000-000000000802';
  await db.execute(sql`insert into workspaces (id,name,slug) values (${a},'Radar A','radar-a'),(${b},'Radar B','radar-b') on conflict do nothing`);
  for (const ws of [a,b]) { await db.execute(sql`insert into customers (workspace_id,id,status,source_namespace,first_seen_at,last_seen_at) values (${ws},'c1','identified','test',now(),now()),(${ws},'c2','identified','test',now(),now()),(${ws},'c3','identified','test',now(),now()),(${ws},'c4','anonymous','test',now(),now())`); await db.execute(sql`insert into outcome_definitions (workspace_id,id,outcome_namespace,outcome_key,name,kind,definition,source_namespace) values (${ws},'purchase','canonical','purchase','Purchase','event','{}'::jsonb,'test')`); await db.execute(sql`insert into customer_traits (workspace_id,id,customer_id,trait_namespace,trait_key,value_type,value,source_namespace,observed_at) values (${ws},'t1','c1','canonical','country','string','"BR"'::jsonb,'test',now()),(${ws},'t2','c2','canonical','country','string','"BR"'::jsonb,'test',now()),(${ws},'t3','c3','canonical','country','string','"US"'::jsonb,'test',now())`); await db.execute(sql`insert into customer_outcomes (workspace_id,id,customer_id,outcome_definition_id,outcome_namespace,outcome_key,dedupe_key,event_id,source_namespace,observed_at) values (${ws},'o1','c1','purchase','canonical','purchase','d1','e1','test',now()),(${ws},'o2','c3','purchase','canonical','purchase','d2','e2','test',now())`); }
  await db.execute(sql`insert into connector_connections (workspace_id,id,provider,role,display_name,lifecycle_state,credential_status,capabilities) values (${a},'dest','test','destination','Destination','disconnected','valid','["activation"]'::jsonb),(${b},'dest','test','destination','Destination','healthy','valid','["activation"]'::jsonb)`);
  const service=new RadarService(db, { evaluate: async()=>({criticalCount:0}) } as never);
  assert.equal(await service.audienceCount(a,{version:1,op:'identified'}),3); assert.equal(await service.audienceCount(a,{version:1,op:'trait',key:'country',operator:'eq',value:'BR'}),2); assert.equal(await service.audienceCount(a,{version:1,op:'outcome_occurred',outcomeDefinitionId:'purchase'}),2); assert.equal(await service.audienceCount(a,{version:1,op:'and',children:[{version:1,op:'trait',key:'country',operator:'eq',value:'BR'},{version:1,op:'outcome_occurred',outcomeDefinitionId:'purchase'}]}),1); assert.equal(await service.audienceCount(a,{version:1,op:'or',children:[{version:1,op:'trait',key:'country',operator:'eq',value:'BR'},{version:1,op:'outcome_occurred',outcomeDefinitionId:'purchase'}]}),3);
  const created=await service.create(a,{name:'Purchase radar',outcomeDefinitionId:'purchase',predictionWindowDays:30,activationDestination:{connectionId:'dest',capability:'activation'}}) as {radar:{id:string}}; const id=created.radar.id; await assert.rejects(()=>service.create(a,{name:'Cross',outcomeDefinitionId:'purchase',predictionWindowDays:7,activationDestination:{connectionId:'dest-other',capability:'activation'}}));
  await db.execute(sql`update radars set status='ready_to_train' where workspace_id=${a} and id=${id}`); const [one,two]=await Promise.all([service.train(a,id,'same-key'),service.train(a,id,'other-key')]); assert.equal((one as {id:string}).id,(two as {id:string}).id); const request=one as {id:string;definition_version:number}; await service.reportTrainingResult(a,id,1,request.id,{status:'succeeded',modelReference:'model-v1'}); const active=await service.get(a,id) as {radar:{status:string}}; assert.equal(active.radar.status,'active'); await service.patch(a,id,{predictionWindowDays:14}); await assert.rejects(()=>service.reportTrainingResult(a,id,1,request.id,{status:'succeeded',modelReference:'late'}));
  await db.execute(sql`delete from radar_training_requests where workspace_id in (${a},${b})`); await db.execute(sql`delete from radar_definition_versions where workspace_id in (${a},${b})`); await db.execute(sql`delete from radars where workspace_id in (${a},${b})`); await db.execute(sql`delete from customer_outcomes where workspace_id in (${a},${b})`); await db.execute(sql`delete from customer_traits where workspace_id in (${a},${b})`); await db.execute(sql`delete from outcome_definitions where workspace_id in (${a},${b})`); await db.execute(sql`delete from connector_connections where workspace_id in (${a},${b})`); await db.execute(sql`delete from customers where workspace_id in (${a},${b})`); await db.execute(sql`delete from workspaces where id in (${a},${b})`); await closeDb(db);
});
