import { boolean, index, jsonb, pgTable, primaryKey, text, timestamp, numeric, integer, uniqueIndex } from 'drizzle-orm/pg-core';

/** Order 110: immutable decision-time fact; operational facts are separate rows. */
export const decisionRecords = pgTable('decision_records', {
  workspaceId: text('workspace_id').notNull(), id: text('id').notNull(), customerId: text('customer_id').notNull(),
  currentCustomerId: text('current_customer_id'), radarId: text('radar_id').notNull(), definitionVersion: integer('definition_version').notNull(),
  modelVersionId: text('model_version_id').notNull(), scoreBatchId: text('score_batch_id').notNull(), scoreCutoff: timestamp('score_cutoff',{withTimezone:true}).notNull(),
  opportunityBatchId: text('opportunity_batch_id'), opportunityRowId: text('opportunity_row_id'), targetOutcomeDefinitionId: text('target_outcome_definition_id').notNull(),
  policyVersion: text('policy_version').notNull(), triggerSource: text('trigger_source').notNull(), selectedActionType: text('selected_action_type').notNull(), selectedActionVersion: integer('selected_action_version').notNull().default(1),
  contextSnapshotId: text('context_snapshot_id').notNull(), decisionBatchId: text('decision_batch_id'), correlationId: text('correlation_id').notNull(), idempotencyKey: text('idempotency_key').notNull(), rewardWindowEnd: timestamp('reward_window_end',{withTimezone:true}).notNull(), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
}, t=>({pk:primaryKey({columns:[t.workspaceId,t.id]}), idempotency:uniqueIndex('decision_records_idempotency_uq').on(t.workspaceId,t.idempotencyKey), list:index('decision_records_list_idx').on(t.workspaceId,t.radarId,t.createdAt)}));
export const decisionContextSnapshots = pgTable('decision_context_snapshots',{workspaceId:text('workspace_id').notNull(),id:text('id').notNull(),schemaVersion:integer('schema_version').notNull(),snapshot:jsonb('snapshot').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()},t=>({pk:primaryKey({columns:[t.workspaceId,t.id]} )}));
export const decisionEligibleActions = pgTable('decision_eligible_actions',{workspaceId:text('workspace_id').notNull(),decisionId:text('decision_id').notNull(),actionType:text('action_type').notNull(),actionVersion:integer('action_version').notNull(),parameters:jsonb('parameters').notNull().default({})},t=>({pk:primaryKey({columns:[t.workspaceId,t.decisionId,t.actionType]})}));
export const actionExecutions = pgTable('action_executions',{workspaceId:text('workspace_id').notNull(),id:text('id').notNull(),decisionId:text('decision_id').notNull(),actionType:text('action_type').notNull(),actionVersion:integer('action_version').notNull(),connectionId:text('connection_id'),correlationId:text('correlation_id').notNull(),idempotencyKey:text('idempotency_key').notNull(),providerOperationKey:text('provider_operation_key').notNull(),status:text('status').notNull(),remoteId:text('remote_id'),counts:jsonb('counts').notNull().default({}),failureCategory:text('failure_category'),attempts:integer('attempts').notNull().default(0),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>({pk:primaryKey({columns:[t.workspaceId,t.id]}),idem:uniqueIndex('action_executions_idempotency_uq').on(t.workspaceId,t.idempotencyKey),decision:index('action_executions_decision_idx').on(t.workspaceId,t.decisionId),status:index('action_executions_status_idx').on(t.workspaceId,t.status,t.updatedAt)}));
export const actionExecutionAttempts = pgTable('action_execution_attempts',{workspaceId:text('workspace_id').notNull(),executionId:text('execution_id').notNull(),attempt:integer('attempt').notNull(),status:text('status').notNull(),remoteId:text('remote_id'),failureCategory:text('failure_category'),providerOperationKey:text('provider_operation_key').notNull(),observedAt:timestamp('observed_at',{withTimezone:true}).notNull().defaultNow()},t=>({pk:primaryKey({columns:[t.workspaceId,t.executionId,t.attempt]}),operation:index('action_execution_attempts_operation_idx').on(t.workspaceId,t.providerOperationKey,t.observedAt)}));
export const exposureObservations = pgTable('exposure_observations',{workspaceId:text('workspace_id').notNull(),id:text('id').notNull(),decisionId:text('decision_id').notNull(),executionId:text('execution_id'),kind:text('kind').notNull(),sourceConfidence:text('source_confidence').notNull(),providerEventId:text('provider_event_id'),occurredAt:timestamp('occurred_at',{withTimezone:true}),ingestedAt:timestamp('ingested_at',{withTimezone:true}).notNull().defaultNow()},t=>({pk:primaryKey({columns:[t.workspaceId,t.id]}),dedup:uniqueIndex('exposure_observations_event_uq').on(t.workspaceId,t.providerEventId),decision:index('exposure_observations_decision_idx').on(t.workspaceId,t.decisionId,t.occurredAt)}));
export const rewardObservations = pgTable('reward_observations',{workspaceId:text('workspace_id').notNull(),id:text('id').notNull(),decisionId:text('decision_id').notNull(),version:integer('version').notNull(),outcomeCount:integer('outcome_count').notNull(),observedValue:numeric('observed_value'),currency:text('currency'),firstOutcomeAt:timestamp('first_outcome_at',{withTimezone:true}),lastOutcomeAt:timestamp('last_outcome_at',{withTimezone:true}),final:boolean('final').notNull().default(false),rewardFunctionVersion:text('reward_function_version').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()},t=>({pk:primaryKey({columns:[t.workspaceId,t.id]}),versionUq:uniqueIndex('reward_observations_version_uq').on(t.workspaceId,t.decisionId,t.version),finality:index('reward_observations_finality_idx').on(t.workspaceId,t.final,t.decisionId,t.version)}));
export const decisionRewardReconciliationCheckpoints = pgTable('decision_reward_reconciliation_checkpoints',{workspaceId:text('workspace_id').primaryKey(),lastDecisionId:text('last_decision_id'),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()});
