'use client';

import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowRight, CheckCircle2, LoaderCircle, RefreshCw, TriangleAlert } from 'lucide-react';
import { api } from '@/lib/api';

interface Props { workspaceId: string; onComplete: (workspaceName: string) => void; onCancel: () => void; showCancelButton: boolean }
type Path = 'ecommerce' | 'saas' | 'custom';
type Connection = { id: string; provider: string; displayName: string; lifecycleState: string; credentialStatus: string };
type State = { progress: Record<string, any>; source: { state: string; healthy: boolean; provider: string | null }; ttfvMs: number | null; recommendations: Record<Path, string[]>; readiness?: any; counts?: Record<string, number>; detected?: boolean };
const labels: Record<Path, [string, string]> = { ecommerce: ['Loja / ecommerce', 'Shopify, Stripe e Klaviyo'], saas: ['Assinatura / SaaS', 'Stripe, HubSpot e eventos do produto'], custom: ['Eventos personalizados / API', 'Truvo Events ou API de ingestão'] };

export default function OnboardingFlow({ workspaceId, onComplete, onCancel, showCancelButton }: Props) {
  const [state, setState] = useState<State | null>(null); const [connections, setConnections] = useState<Connection[]>([]);
  const [name, setName] = useState(''); const [outcomes, setOutcomes] = useState<Array<{ id: string; name: string }>>([]); const [outcomeId, setOutcomeId] = useState('');
  const [radarName, setRadarName] = useState('Meu primeiro Radar'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const generation = useRef(0); const pending = useRef<AbortController | null>(null);
  const load = useCallback(async () => {
    const requestGeneration = generation.current; const controller = new AbortController(); pending.current?.abort(); pending.current = controller;
    const current = await api<State>('/v1/onboarding', { signal: controller.signal });
    const [nextConnections, available] = await Promise.all([
      workspaceId ? api<Connection[]>(`/v1/workspaces/${workspaceId}/connectors/connections`, { signal: controller.signal }).catch(() => []) : [],
      api<Array<{ id: string; name: string }>>('/v1/radars/metadata/outcomes', { signal: controller.signal }).catch(() => []),
    ]);
    if (controller.signal.aborted || requestGeneration !== generation.current) return;
    setState(current); setConnections(nextConnections); setOutcomes(available); setOutcomeId(available[0]?.id || '');
  }, [workspaceId]);
  useEffect(() => {
    generation.current += 1; pending.current?.abort(); setState(null); setConnections([]); setOutcomes([]); setOutcomeId(''); setError(''); setBusy(false);
    void load().catch((e) => { if ((e as Error).name !== 'AbortError') setError((e as Error).message); });
    return () => { generation.current += 1; pending.current?.abort(); };
  }, [workspaceId, load]);
  useEffect(() => { if (!state || !['syncing', 'waiting_for_data', 'blocked'].includes(String(state.progress.status))) return; const timer = window.setInterval(() => void load(), 5000); return () => clearInterval(timer); }, [state, load]);
  const act = async (path: string, body?: unknown) => { const requestGeneration = generation.current; const controller = new AbortController(); pending.current?.abort(); pending.current = controller; setBusy(true); setError(''); try { const next = await api<State>(path, { method: 'POST', body: JSON.stringify(body ?? {}), signal: controller.signal }); if (!controller.signal.aborted && requestGeneration === generation.current) setState(next); } catch (e) { if ((e as Error).name !== 'AbortError' && requestGeneration === generation.current) setError(e instanceof Error ? e.message : 'Não foi possível continuar'); } finally { if (requestGeneration === generation.current) setBusy(false); } };
  if (!state) return error
    ? <div className="mx-auto max-w-3xl rounded-xl border border-rose-200 bg-rose-50 p-6 text-rose-900" role="alert">{error}</div>
    : <div className="mx-auto max-w-3xl p-10 text-center" role="status"><LoaderCircle className="mx-auto animate-spin" /> Carregando seu progresso…</div>;
  const step = String(state.progress.current_step); const path = state.progress.selected_path as Path | null;
  const compatible = connections.filter((c) => !path || state.recommendations[path].includes(c.provider));
  return <section className="mx-auto my-6 max-w-3xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl" aria-labelledby="onboarding-title" data-testid="onboarding-flow">
    <header className="border-b border-slate-100 p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-700">Primeiros passos</p><h1 id="onboarding-title" className="mt-1 text-2xl font-bold text-slate-900">Conheça quem vai comprar em seguida</h1><p className="mt-2 text-sm text-slate-600">Conecte Contexto → verifique os dados → crie seu primeiro Radar.</p></div>{showCancelButton && <button onClick={onCancel} className="rounded-lg px-3 py-2 text-sm text-slate-600 focus:outline-none focus:ring-2 focus:ring-teal-600">Sair</button>}</div>
      <ol className="mt-6 grid grid-cols-3 gap-2 text-xs font-semibold" aria-label="Progresso"><li className="rounded-lg bg-teal-50 p-2 text-teal-800">1. Conectar Contexto</li><li className="rounded-lg bg-slate-50 p-2">2. Verificar dados</li><li className="rounded-lg bg-slate-50 p-2">3. Criar Radar</li></ol></header>
    <div className="space-y-5 p-5 sm:p-7">
      {error && <div role="alert" className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900"><TriangleAlert className="h-5 w-5 shrink-0" />{error}</div>}
      {step === 'workspace_basics' && <form onSubmit={(e) => { e.preventDefault(); void act('/v1/onboarding/start', { workspaceName: name || undefined }); }} className="space-y-4"><div><label htmlFor="workspace-name" className="text-sm font-bold">Nome do workspace</label><input id="workspace-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Minha empresa" className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3 focus:ring-2 focus:ring-teal-600" /></div><button disabled={busy} className="rounded-xl bg-slate-900 px-5 py-3 font-bold text-white disabled:opacity-50">Continuar <ArrowRight className="inline h-4 w-4" /></button></form>}
      {step === 'choose_path' && <div><h2 className="text-lg font-bold">Como sua empresa gera receita?</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{(Object.keys(labels) as Path[]).map((p) => <button key={p} disabled={busy} onClick={() => void act('/v1/onboarding/path', { path: p })} className="rounded-xl border border-slate-200 p-4 text-left hover:border-teal-600 focus:ring-2 focus:ring-teal-600"><span className="block font-bold">{labels[p][0]}</span><span className="mt-1 block text-xs text-slate-500">{labels[p][1]}</span></button>)}</div></div>}
      {step === 'connect_context' && path === 'custom' && <div className="space-y-4"><h2 className="text-lg font-bold">Envie um evento real</h2><p className="text-sm text-slate-600">Crie ou reutilize uma chave em Configurações e envie dados pela API/Truvo Events. A criação da chave, sozinha, não marca esta etapa como concluída.</p><button disabled={busy} onClick={() => void act('/v1/onboarding/verify')} className="rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Verificar dados recebidos</button></div>}
      {step === 'connect_context' && path !== 'custom' && <div className="space-y-4"><h2 className="text-lg font-bold">Conecte uma fonte existente</h2>{compatible.length === 0 ? <div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Nenhuma fonte compatível foi configurada. Abra Integrações, autorize uma fonte e volte; somente uma conexão válida e saudável avançará.</div> : compatible.map((c) => <button key={c.id} disabled={busy} onClick={() => void act('/v1/onboarding/connection', { connectionId: c.id })} className="flex w-full items-center justify-between rounded-xl border p-4 text-left focus:ring-2 focus:ring-teal-600"><span><b>{c.displayName}</b><small className="block text-slate-500">{c.provider} · {c.lifecycleState} · credencial {c.credentialStatus}</small></span><ArrowRight /></button>)}<button onClick={onCancel} className="text-sm font-semibold text-teal-700">Abrir Integrações</button></div>}
      {step === 'verify_data' && <div className="space-y-4"><h2 className="text-lg font-bold">Estamos verificando seu Contexto</h2><p className="text-sm text-slate-600">Fonte: {state.source.state}. O avanço depende de clientes, resultados ou eventos canônicos realmente persistidos.</p>{state.progress.last_error_remediation && <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{state.progress.last_error_remediation}</p>}<button disabled={busy} onClick={() => void act('/v1/onboarding/verify')} className="rounded-xl bg-teal-700 px-5 py-3 font-bold text-white"><RefreshCw className="mr-2 inline h-4 w-4" />Verificar agora</button></div>}
      {step === 'readiness' && <div className="space-y-4"><h2 className="text-lg font-bold">Dados encontrados</h2><p className="text-sm text-slate-600">Agora calcularemos Data Health, cobertura de Contexto, identidade e prontidão para previsão usando os dados reais.</p><button disabled={busy} onClick={() => void act('/v1/onboarding/readiness', {})} className="rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Ver prontidão</button></div>}
      {step === 'create_radar' && <div className="space-y-4"><h2 className="text-lg font-bold">Crie seu primeiro Radar</h2>{state.readiness?.radarReadiness?.status === 'not_ready' && <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Encontramos dados, mas ainda não há histórico suficiente para previsões. Você pode criar o Radar agora e validar novamente depois.</p>}<label className="block text-sm font-bold">Nome<input value={radarName} onChange={(e) => setRadarName(e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="block text-sm font-bold">Resultado alvo<select value={outcomeId} onChange={(e) => setOutcomeId(e.target.value)} className="mt-1 w-full rounded-xl border p-3">{outcomes.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><button disabled={busy || !outcomeId} onClick={() => void act('/v1/onboarding/radar', { name: radarName, outcomeDefinitionId: outcomeId, predictionWindowDays: 30, idempotencyKey: `first-radar-${workspaceId}` })} className="rounded-xl bg-slate-900 px-5 py-3 font-bold text-white disabled:opacity-50">Criar Radar real</button></div>}
      {step === 'completed' && <div className="space-y-4 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600" /><h2 className="text-xl font-bold">Seu primeiro Radar foi criado</h2><p className="text-sm text-slate-600">Abra o Radar para acompanhar a prontidão real e o próximo passo. Nenhuma oportunidade foi fabricada.</p><button onClick={() => onComplete(name)} className="rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Ver Radars</button>{state.ttfvMs != null && <p className="text-xs text-slate-500">Tempo até primeiro valor: {Math.round(state.ttfvMs / 1000)}s</p>}</div>}
    </div></section>;
}
